/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;


import controller.UIController;
import domen.OpstiDomenskiObjekat;
import domen.Salon;
import domen.Vlasnik;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Mihajlo Popovic
 */
public class VlasnikMainForm extends javax.swing.JFrame {

    /**
     * Creates new form VlasnikMainForm
     */
    private Vlasnik vlasnik;
    private Salon salon;
    
    public VlasnikMainForm(Vlasnik ulogovan) {
        initComponents();
        setLocationRelativeTo(null);
        this.vlasnik = ulogovan;
        jLabel1.setText("Dobrodosli "+ vlasnik.getIme()+"!");
        salon = new Salon();
        salon.setVlasnik(vlasnik);
        try {
            OpstiDomenskiObjekat odo  =  UIController.getInstance().getOneSalon(salon);
            salon = (Salon) odo;
            System.out.println("Salon: "+ salon);
        } catch (Exception ex) {
            Logger.getLogger(VlasnikMainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDodajTermine = new javax.swing.JButton();
        btnPretraziTermine = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vlasnik Forma");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        btnDodajTermine.setText("Dodaj Termine");
        btnDodajTermine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTermineActionPerformed(evt);
            }
        });

        btnPretraziTermine.setText("Pretrazi Termine");
        btnPretraziTermine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziTermineActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodajTermine, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPretraziTermine, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(btnPretraziTermine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajTermine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajTermineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTermineActionPerformed
        // TODO add your handling code here:
        new DodavanjeTermina(this,true,salon).setVisible(true);
        
         
        
    }//GEN-LAST:event_btnDodajTermineActionPerformed

    private void btnPretraziTermineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziTermineActionPerformed
        // TODO add your handling code here:
        new PretrazivanjeTermina(salon).setVisible(true);
        
    }//GEN-LAST:event_btnPretraziTermineActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTermine;
    private javax.swing.JButton btnPretraziTermine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
